# config for scRNA-seq snakemake pipeline #
# setup for human datasets #

DATA: "../data/"

PROJECTS: 
  - 'lna_gene/jurkat_gene_pulldown_dna'
  - 'lna_gene/jurkat_gene_pulldown_lna'
  - 'lna_gene/jurkat_original'

GENOME_FA:
  "/beevol/home/riemondy/Projects/shared_dbases/genomes/GRCh38.primary_assembly.genome.fa"

STAR_IDX:
  "/beevol/home/riemondy/Projects/shared_dbases/star/gencode_GRCh38/"

TRANSCRIPTS:
  "/beevol/home/riemondy/Projects/shared_dbases/annotation/gencode.v25.annotation.gtf"

IDS:
  jurkat_gene_pulldown_dna: "JH112_S58_L001"
  jurkat_gene_pulldown_lna: "Jh111_S13_L001"
  jurkat_original: 'JurkatExp_S1_L001'

LIB_MAP:
  jurkat_gene_pulldown_dna: "PBMC"
  jurkat_gene_pulldown_lna: "PBMC"
  jurkat_original: "PBMC"


PBMC:
  bcs: "/beevol/home/riemondy/Projects/scrna-subsets/data/lna_gene/jurkat_gene_pulldown_dna/fastq/original/barcodes.tsv"
  seq_extract: " 1 16 17 26 '_' "  
  fc_params: " -p -s 1 "

