
DATA: "../data/"
DBASES: "../dbases/"

PROJECTS: 
    - 'tcr_resampling/resampled'
    - 'tcr_resampling/original'
IDS:
    resampled: "JH109_S46_L004"
    original: "Tcell_S1_L001"

BCS_TO_KEEP: "/beevol/home/riemondy/Projects/subsampled_scRNA/data/tcr_resampling/resampled/fastq/original/barcodes.txt"
REF_FA: "/beevol/home/riemondy/Projects/10x_data/tcr/results/2018-05-18_jurkat_raji/VDJ_Tcell/outs/consensus.fasta"

