# config for scRNA-SEQ snakemake pipeline #
# setup for mouse-human datasets #

DATA: "../data/"

PROJECTS: 
    # - 'standard'
    # - 'original'
    # - 'biotinylated'
    # - 'phosphorothioate'
  - 'original_10x'
  - 'lna_pulldown'
  - 'lna_control'

GENOME_FA:
  "../../shared_dbases/genomes/human_mouse_mix/human_mouse_gencode_hm38_renamed.fa"

STAR_IDX:
  "../../shared_dbases/star/renamed_GRChm38_full/"

TRANSCRIPTS:
  "../../shared_dbases/annotation/human_mouse_mix/human_mouse_gencode_vm11_v25_renamed.gtf"

TRANSCRIPTS_BED:
  "../../shared_dbases/annotation/human_mouse_mix/human_mouse_gencode_vm11_v25_renamed.bed"

IDS:
    #  standard: "1_AGGCAGAA_L001" 
#  original: "Bentley701_TAAGGCGA_L068"
#  biotinylated: "BIOTINTEST_AGGCAGAA_L001"
#  phosphorothioate: "PoolJH76_AGGCAGAA_L001"
  original_10x: "Control_S1_L001"
  lna_pulldown: "3_TCCTGA_L001"
  lna_control: "4_AGGCTA_L001"

LIB_MAP:
    #  standard: "PCR"
#  original: "PCR"
#  biotinylated: "PCR"
#  phosphorothioate: "PCR"
  original_10x: "LNA"
  lna_pulldown: "LNA"
  lna_control: "LNA"


PCR:
  bcs: "/vol3/home/riemondy/Projects/subsampled_scRNA/data/original/fastq/original/well_data_barcode_keys.txt"
  seq_extract: " 1 11 12 21 "  

LNA:
  bcs: "/vol3/home/riemondy/Projects/subsampled_scRNA/data/original_10x/fastq/original/barcodes_from_10x_run.txt"
  seq_extract: " 1 16 17 26 "  
