# config for scRNA-SEQ snakemake pipeline #
# setup for mouse-human datasets #

DATA: "../data/"

PROJECTS: 
  - 'pcr/standard'
  - 'pcr/original'
  - 'pcr/biotinylated'
  - 'pcr/phosphorothioate'
  - 'lna_cell/mh_mix/original_10x'
  - 'lna_cell/mh_mix/mouse_human_cell_pulldown' 
  - 'lna_cell/public_10x_mh'

GENOME_FA:
  "/beevol/home/riemondy/Projects/shared_dbases/genomes/human_mouse_mix/human_mouse_gencode_hm38_renamed.fa"

STAR_IDX:
  "/beevol/home/riemondy/Projects/shared_dbases/star/renamed_GRChm38_full/"

TRANSCRIPTS:
  "/beevol/home/riemondy/Projects/shared_dbases/annotation/human_mouse_mix/human_mouse_gencode_vm11_v25_renamed.gtf"

TRANSCRIPTS_BED:
  "/beevol/home/riemondy/Projects/shared_dbases/annotation/human_mouse_mix/human_mouse_gencode_vm11_v25_renamed.bed"

IDS:
  standard: "1_AGGCAGAA_L001" 
  original: "Bentley701_TAAGGCGA_L068"
  biotinylated: "BIOTINTEST_AGGCAGAA_L001"
  phosphorothioate: "PoolJH76_AGGCAGAA_L001"
  original_10x: "Control_S1_L001"
  mouse_human_cell_pulldown: "Control_H3_S1_L001"
  public_10x_mh: "hgmm_S1_L001"

LIB_MAP:
  standard: "PCR"
  original: "PCR"
  biotinylated: "PCR"
  phosphorothioate: "PCR"
  original_10x: "LNA"
  mouse_human_cell_pulldown: "LNA"
  public_10x_mh: "public_data_10x"
  
PCR:
  bcs: "/beevol/home/riemondy/Projects/subsampled_scRNA/data/pcr/original/fastq/original/well_data_barcode_keys.txt"
  seq_extract: " 1 11 12 21 "  
  fc_params: " -s 1 "

LNA:
  bcs: "/beevol/home/riemondy/Projects/subsampled_scRNA/data/lna_cell/mh_mix/original_10x/fastq/original/barcodes_from_10x_run.txt"
  seq_extract: " 1 16 17 26 "  
  fc_params: " -s 1 "

public_data_10x:
  bcs: "/beevol/home/riemondy/Projects/subsampled_scRNA/data/lna_cell/public_10x_mh/fastq/original/barcodes.txt"  
  seq_extract: " 1 16 17 26 "  
  fc_params: " -s 1 "
