# config for scRNA-SEQ snakemake pipeline #
# setup for mouse-human datasets #
 
PROJECTS: 
  '../data/biotinylated'

GENOME_FA:
  "../../shared_dbases/genomes/human_mouse_mix/human_mouse_gencode_hm38_renamed.fa"

STAR_IDX:
  "../../shared_dbases/star/renamed_GRChm38_full/"

TRANSCRIPTS:
  "../../shared_dbases/annotation/human_mouse_mix/human_mouse_gencode_vm11_v25_renamed.gtf"

TRANSCRIPTS_BED:
  "../../shared_dbases/annotation/human_mouse_mix/human_mouse_gencode_vm11_v25_renamed.bed"

IDS:
  - BIOTINTEST_AGGCAGAA_L001 

BCS:
  "well_data"
