# config for scRNA-seq snakemake pipeline #
# setup for human datasets #

DATA: "../data/"

PROJECTS: 
  - 'lna_cell/pbmc_expt/kirkpatrick'
  - 'lna_cell/pbmc_expt/mkcell_pulldown'
  - 'lna_gene/mk_gene_pulldown'

GENOME_FA:
  "/beevol/home/riemondy/Projects/shared_dbases/genomes/GRCh38.primary_assembly.genome.fa"

STAR_IDX:
  "/beevol/home/riemondy/Projects/shared_dbases/star/gencode_GRCh38/"

TRANSCRIPTS:
  "/beevol/home/riemondy/Projects/shared_dbases/annotation/gencode.v25.annotation.gtf"

IDS:
  kirkpatrick: "C2_S1_L002"
  mk_gene_pulldown: "2_Dipaola_Kirkpatrick_C2_S1_L002"
  mkcell_pulldown: "2_Dipaola_Kirkpatrick_C2_S1_L001"

LIB_MAP:
  kirkpatrick: "LNA"
  mk_gene_pulldown: "LNA"
  mkcell_pulldown: "LNA"

LNA:
  bcs: "/beevol/home/riemondy/Projects/subsampled_scRNA/data/lna_cell/pbmc_expt/kirkpatrick/fastq/original/barcodes_from_10x_run.txt"
  seq_extract: " 1 16 17 26 "  
  fc_params: " -s 1 "

