
DATA: "../data/"
DBASES: "../dbases/"

PROJECTS: 
    - 'tcr_resampling/resampled'
    - 'tcr_resampling/original'
IDS:
    resampled: "JH109_S46_L004"
    original: "Tcell_S1_L001"

BCS_TO_KEEP: "/beevol/home/riemondy/Projects/scrna-subsets/data/tcr_resampling/resampled/fastq/original/barcodes.txt"
REF_FA: "/beevol/home/riemondy/Projects/scrna-subsets/data/tcr_resampling/original/VDJ_newcellranger_Tcell/outs/consensus.fasta"
TCRA_CONTIG:
    "clonotype2_consensus_1"
TCRB_CONTIG:
    "clonotype1_consensus_1"
